//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetupPage
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Logo { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string BannerMassage { get; set; }
        public string TermsOfUse { get; set; }
        public string PrivacyPolicy { get; set; }
        public string Url { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
