//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eRentEntities : DbContext
    {
        public eRentEntities()
            : base("name=eRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanySetupPage> CompanySetupPages { get; set; }
        public virtual DbSet<equipmentDetail> equipmentDetails { get; set; }
        public virtual DbSet<feesDetail> feesDetails { get; set; }
        public virtual DbSet<Forklift> Forklifts { get; set; }
        public virtual DbSet<ForkliftsModel> ForkliftsModels { get; set; }
        public virtual DbSet<ForkliftsModelCharge> ForkliftsModelCharges { get; set; }
        public virtual DbSet<ForkliftsModelTransportation> ForkliftsModelTransportations { get; set; }
        public virtual DbSet<Mapping_ForkliftsModelCharges_Reservation> Mapping_ForkliftsModelCharges_Reservation { get; set; }
        public virtual DbSet<Mapping_ForkliftsModelTransportation_Reservation> Mapping_ForkliftsModelTransportation_Reservation { get; set; }
        public virtual DbSet<Mapping_PricingNationalAccount_Reservation> Mapping_PricingNationalAccount_Reservation { get; set; }
        public virtual DbSet<Mapping_PricingStandard_Reservation> Mapping_PricingStandard_Reservation { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationAPI> ReservationAPIs { get; set; }
        public virtual DbSet<ReservationDtl> ReservationDtls { get; set; }
        public virtual DbSet<ReservationHdr> ReservationHdrs { get; set; }
        public virtual DbSet<ReservationStatu> ReservationStatus { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
