//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class feesDetail
    {
        public int id { get; set; }
        public Nullable<int> equipmentDetailID { get; set; }
        public string charge { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual equipmentDetail equipmentDetail { get; set; }
    }
}
