//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForkliftsModelTransportation
    {
        public int Id { get; set; }
        public int ForkliftsModelId { get; set; }
        public decimal PickUpFees { get; set; }
        public decimal DropOff_PickUp_Fees { get; set; }
        public decimal DropOffOnly { get; set; }
        public decimal PickUpOnly { get; set; }
        public decimal LossDamageWaiver { get; set; }
    
        public virtual ForkliftsModel ForkliftsModel { get; set; }
    }
}
