//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForkliftsModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForkliftsModel()
        {
            this.equipmentDetails = new HashSet<equipmentDetail>();
            this.ForkliftsModelCharges = new HashSet<ForkliftsModelCharge>();
            this.ForkliftsModelTransportations = new HashSet<ForkliftsModelTransportation>();
            this.Reservations = new HashSet<Reservation>();
            this.ReservationDtls = new HashSet<ReservationDtl>();
        }
    
        public int Id { get; set; }
        public int ForkliftsId { get; set; }
        public string Picture { get; set; }
        public string Make { get; set; }
        public decimal Capacity { get; set; }
        public string Model { get; set; }
        public decimal MaxMeter { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public int Quantity { get; set; }
        public decimal PricingStandard_Daily { get; set; }
        public decimal PricingStandard_Weekly { get; set; }
        public decimal PricingStandard_Montly { get; set; }
        public decimal PricingNationalAccount_Daily { get; set; }
        public decimal PricingNationalAccount_Weekly { get; set; }
        public decimal PricingNationalAccount_Montly { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipmentDetail> equipmentDetails { get; set; }
        public virtual Forklift Forklift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForkliftsModelCharge> ForkliftsModelCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForkliftsModelTransportation> ForkliftsModelTransportations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationDtl> ReservationDtls { get; set; }
    }
}
