//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping_PricingNationalAccount_Reservation
    {
        public int Id { get; set; }
        public int PricingNationalAccountId { get; set; }
        public int ReservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
