//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Mapping_ForkliftsModelCharges_Reservation = new HashSet<Mapping_ForkliftsModelCharges_Reservation>();
            this.Mapping_ForkliftsModelTransportation_Reservation = new HashSet<Mapping_ForkliftsModelTransportation_Reservation>();
            this.Mapping_PricingNationalAccount_Reservation = new HashSet<Mapping_PricingNationalAccount_Reservation>();
            this.Mapping_PricingStandard_Reservation = new HashSet<Mapping_PricingStandard_Reservation>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ForkliftsModelId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Location { get; set; }
        public string InsurancePicture { get; set; }
        public int ReservationStatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsViewedFlag { get; set; }
    
        public virtual ForkliftsModel ForkliftsModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping_ForkliftsModelCharges_Reservation> Mapping_ForkliftsModelCharges_Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping_ForkliftsModelTransportation_Reservation> Mapping_ForkliftsModelTransportation_Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping_PricingNationalAccount_Reservation> Mapping_PricingNationalAccount_Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping_PricingStandard_Reservation> Mapping_PricingStandard_Reservation { get; set; }
        public virtual User User { get; set; }
    }
}
