//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationAPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationAPI()
        {
            this.equipmentDetails = new HashSet<equipmentDetail>();
        }
    
        public int id { get; set; }
        public string documentNumber { get; set; }
        public string customerNumber { get; set; }
        public string customerPO { get; set; }
        public string location { get; set; }
        public string comments { get; set; }
        public string insurance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipmentDetail> equipmentDetails { get; set; }
    }
}
