//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CompanySetupPages = new HashSet<CompanySetupPage>();
            this.Notifications = new HashSet<Notification>();
            this.Reservations = new HashSet<Reservation>();
            this.ReservationHdrs = new HashSet<ReservationHdr>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int RoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Image { get; set; }
        public System.DateTime DOB { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public int StateID { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string CompanyAccountInformation { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string PasswordRecoveryCode { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> TokenIssueDate { get; set; }
        public Nullable<System.DateTime> TokenExpiryDate { get; set; }
        public string FCMDeviceToken { get; set; }
        public string SecuredKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySetupPage> CompanySetupPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationHdr> ReservationHdrs { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
